name: Alembic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  alembic_migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_pass
          POSTGRES_DB: ci_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ci_user -d ci_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary alembic

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ci_user; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run Alembic migrations
        env:
          DATABASE_URL: {{env.DATABASE_URL}}
        run: alembic upgrade head

      - name: Print final database schema
        env:
          DATABASE_URL: {{env.DATABASE_URL}}
        run: |
          echo "=== Database Schema ==="
          # 使用 pg_dump 打印所有表结构和约束
          PGPASSWORD=ci_pass pg_dump -U ci_user -h localhost -s ci_db
