name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DATABASE_URL: postgresql+psycopg2://${{ vars.POSTGRES_USER }}:${{ vars.POSTGRES_PASSWORD }}@localhost:5432/${{ vars.POSTGRES_DB }}

jobs:
  alembic_migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ vars.POSTGRES_USER }} -d ${{ vars.POSTGRES_DB }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary alembic

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Print final database schema
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          PGPASSWORD: ${{ vars.POSTGRES_PASSWORD }}
        run: |
          echo "=== Database Schema ==="
          pg_dump -U $POSTGRES_USER -h localhost -s $POSTGRES_DB
